# 测试环境配置
server:
  port: 8080

# Spring配置
spring:
{% if config.tech_stack.database == 'mysql' %}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://test-db-host:3306/{{ config.name | snake_case }}_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: test_user
    password: test_password
{% elif config.tech_stack.database == 'postgresql' %}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://test-db-host:5432/{{ config.name | snake_case }}_test
    username: test_user
    password: test_password
{% endif %}
{% if 'redis' in config.tech_stack.cache %}
  redis:
    host: test-redis-host
    port: 6379
    password: 
    database: 1
{% endif %}
{% if 'rabbitmq' in config.tech_stack.mq %}
  rabbitmq:
    host: test-rabbitmq-host
    port: 5672
    username: test_user
    password: test_password
{% endif %}
{% if 'kafka' in config.tech_stack.mq %}
  kafka:
    bootstrap-servers: test-kafka-host:9092
    consumer:
      group-id: {{ config.name | snake_case }}-test-group
{% endif %}
{% if 'mongodb' in config.tech_stack.nosql %}
  data:
    mongodb:
      uri: mongodb://test-mongo-host:27017/{{ config.name | snake_case }}_test
{% endif %}
{% if 'elasticsearch' in config.tech_stack.nosql %}
  elasticsearch:
    rest:
      uris: http://test-es-host:9200
{% endif %}

# 日志配置
logging:
  level:
    root: info
    {{ config.package }}: debug
{% if config.tech_stack.orm == 'mybatis' %}
    {{ config.package }}.mapper: debug
{% endif %}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/{{ config.name }}-test.log
    max-size: 200MB
    max-history: 60

# Swagger配置
{% if 'swagger' in config.tech_stack.docs %}
swagger:
  enabled: true
{% endif %}

# Actuator配置
{% if 'actuator' in config.tech_stack.monitor %}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
{% endif %}

# 自定义配置
{{ config.name | snake_case }}:
  # 测试环境配置
  debug: true
  # 文件上传配置
  upload:
    base-dir: ./uploads/test
    max-size: 20971520  # 20MB
  # 安全配置
  security:
    jwt:
      secret: {{ config.name | snake_case }}_test_jwt_secret_key
      expiration: 86400000  # 24小时