# 开发环境配置
server:
  port: 8080

# Spring配置
spring:
{% if config.tech_stack.database == 'mysql' %}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{{ config.name | snake_case }}_dev?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
{% elif config.tech_stack.database == 'postgresql' %}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/{{ config.name | snake_case }}_dev
    username: postgres
    password: 123456
{% endif %}
{% if 'redis' in config.tech_stack.cache %}
  redis:
    host: localhost
    port: 6379
    password: 
    database: 0
{% endif %}
{% if 'rabbitmq' in config.tech_stack.mq %}
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
{% endif %}
{% if 'kafka' in config.tech_stack.mq %}
  kafka:
    bootstrap-servers: localhost:9092
{% endif %}
{% if 'mongodb' in config.tech_stack.nosql %}
  data:
    mongodb:
      uri: mongodb://localhost:27017/{{ config.name | snake_case }}_dev
{% endif %}
{% if 'elasticsearch' in config.tech_stack.nosql %}
  elasticsearch:
    rest:
      uris: http://localhost:9200
{% endif %}

# 日志配置
logging:
  level:
    root: info
    {{ config.package }}: debug
    org.springframework.web: debug
    org.springframework.security: debug
{% if config.tech_stack.orm == 'mybatis' %}
    {{ config.package }}.mapper: debug
{% endif %}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n'
  file:
    name: logs/{{ config.name }}-dev.log
    max-size: 100MB
    max-history: 30

# Swagger配置
{% if 'swagger' in config.tech_stack.docs %}
swagger:
  enabled: true
{% endif %}

# 自定义配置
{{ config.name | snake_case }}:
  # 开发环境特殊配置
  debug: true
  # 文件上传配置
  upload:
    base-dir: ./uploads/dev
  # 安全配置
  security:
    # 开发环境可以放宽一些限制
    jwt:
      expiration: 604800000  # 7天